# Generated by Django 3.2.13 on 2022-06-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Видимость комментария'),
        ),
    ]
