# Generated by Django 3.2.13 on 2022-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_comments_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='movies',
            name='video',
            field=models.FileField(null=True, upload_to='video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Видимость комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(),
        ),
    ]
