# Generated by Django 3.2.13 on 2022-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20220615_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='age',
            field=models.SmallIntegerField(null=True, verbose_name='Ограничение по по возрасту'),
        ),
    ]
