# Generated by Django 3.2.13 on 2022-06-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movies_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='date_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
