# Generated by Django 3.2.13 on 2022-06-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movies_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Год выхода'),
        ),
    ]
